name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse tool versions
        uses: wistia/parse-tool-versions@353ac6f3d592af47f8b0b7612a4fa1c87d2fe319

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GOLANG }}

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v${{ env.GOLANGCI_LINT }}
          args: --version

      - name: Install just
        uses: extractions/setup-just@v2
        with:
          just-version: ${{ env.JUST }}

      - name: Run tests
        run: just test

      - name: Check formatting
        run: just format-check

      - name: Run linter
        run: golangci-lint run

      - name: Build
        run: just build

      - name: Run chex on itself
        run: ./bin/chex
